#   _   _   _   __ ____          _
# /  \ |_) |_)  |   |        |/ |_  \/
# \__/ | \ |_) _|   |        |\ |_  |

url: "https://your-site.server.com/" # URL нужного сайта
token: "" # Токен размером в 64 символа (генерируется сам, если пустой)
language: "ru_ru" # YML файл локализации в папке language/
debug-mode: 1 # 0 - только старт/выключение; 1 - старт/выключение + ошибки; 2 - подробный дебаг
logger-mode: 1 # То же самое, что и дебаг-моды, для баз данных
logger-type: "H2" # Тип СУБД для логирования (SQLite, DataBase, H2)
